### ISSUE TITLE
missing readme.md

### ISSUE THREAD

**Issue by esaruoho** [oliverkulpakko/ATMs#1]
got a readme.md for me on this one?

**Comment by oliverkulpakko** [comment]
Still a work in progress, I’ll do a proper readme in a few days. But it’s a very simple app with all Otto-ATMs, an older version of the app has already been released on the app store: https://itunes.apple.com/fi/app/ottomaatit/id945406827?mt=8. This repo is a rewritten version with a better UI.

**Comment by esaruoho** [comment]
@oliverkulpakko cool, could you dump me a testflight version to esaruoho@gmail.com so could give it a shot?

**Comment by oliverkulpakko** [comment]
Just created a basic readme.
I just submitted the build, and it's processing. You should get an email invitation soon (if Apple doesn't decide to randomly review it).

**Comment by oliverkulpakko** [comment]
Ok, apparently Apple reviews all apps that haven't been beta-tested before. It should be available tomorrow or the day after.
